# fly.toml file generated for weathered-snow-5705 on 2023-04-12T19:45:41-06:00

app = "weathered-snow-5705"
kill_signal = "SIGINT"
kill_timeout = 5
primary_region = "yyz"


[processes]
  app = "sh start_with_migrations.sh"
  worker = "npx ts-node scripts/sync.ts"

[env]
  PORT = "8080"

# [mounts]
#   source="database"
#   destination="/data"

[http_service]
  processes = ["app", "worker"]
  internal_port = 8080
  force_https = true

  [http_service.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [http_service.http_options.response.headers]
    Referrer-Policy = "no-referrer"
    Strict-Transport-Security = "max-age=63072000; includeSubDomains"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
  